### ISSUE TITLE
EasyUI的库类太多了

### ISSUE THREAD

**Issue by zhemingxingbu** [easemob/sdkexamples-android#130]
EasyUI库中，引用的jar包里面的类数量都很多，集成的时候很容易出现
类太多的问题
Unable to execute dex: method ID not in [0, 0xffff]: 65536

**Comment by zhanw** [comment]
这些库不用easeui实际你在app中一样会用到这些或者类似的库的，现在google是提供api解决你报错的问题，可以百度一下
