### ISSUE TITLE
把ChatDemoUI 导入Android Studio, 9.PNG报错

### ISSUE THREAD

**Issue by eastwoodwang** [easemob/sdkexamples-android#98]
D:\Workspace\AndroidStudio\ChatDemoUI\app\src\main\res\drawable-hdpi\tab_unread_bg.9.png
Error:No marked region found along edge.
Error:Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Administrator\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 42
Error:Execution failed for task ':app:mergeDebugResources'.
> D:\Workspace\AndroidStudio\ChatDemoUI\app\src\main\res\drawable-hdpi\tab_unread_bg.9.png: Error: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Users\Administrator\AppData\Local\Android\sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 42

**Comment by Cogitate-hzx** [comment]
楼主解决了吗？

**Comment by 839687571** [comment]
draw9patch.bat 修改图片可以解决

**Comment by tankxxl** [comment]
从日志上看，原因是xx.9.png的图片实际上没有标记黑线。
解决的方法是：把图片名字中的.9去掉，修改成xx.png就可以了。。

**Comment by fantasysea** [comment]
我自己编辑了一下.9的图就好了

**Comment by eastwoodwang** [comment]
9.png需要设置边界， 每条边至少设置一个， 注意背景画布大小和图片的大小 最好留几个像素出来 这样才安全

**Comment by zhanw** [comment]
恩，这个以前不知道谁放的图片，9图处理的有点问题，3.0demo的dev分支上已经fix

**Comment by Cogitate-hzx** [comment]
thank you

发自我的 iPhone 7
